services:
  - type: web
    name: ai-brief-generator
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn briefgen.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: ai-brief-generator-1.onrender.com


